In [ ]:
!pip install pandas

In [1]:
import pandas as pd

In [2]:
dga_dataset = pd.read_csv("data/dga_data.csv")
dga_dataset.describe()

         isDGA                      domain            host subclass
count   160000                      159998          160000   160000
unique       2                      159998          159235        9
top        dga  6xzxsw3sokvg1tc752y1a6p0af  droid-life.com    alexa
freq     80000                           1               2    42616

In [3]:
dga_dataset.head()

,isDGA,domain,host,subclass
0,dga,6xzxsw3sokvg1tc752y1a6p0af,6xzxsw3sokvg1tc752y1a6p0af.com,gameoverdga
1,dga,glbtlxwwhbnpxs,glbtlxwwhbnpxs.ru,cryptolocker
2,dga,xxmamopyipbfpk,xxmamopyipbfpk.ru,cryptolocker
3,dga,zfd5szpi18i85wj9uy13l69rg,zfd5szpi18i85wj9uy13l69rg.net,newgoz
4,dga,jpqftymiuver,jpqftymiuver.ru,cryptolocker

In [17]:
dga_dataset.groupby(["isDGA"]).count()

       domain   host  subclass  extension
isDGA
dga     80000  80000     80000      80000
legit   79998  80000     80000      80000

In [16]:
dga_dataset.groupby(["isDGA", "subclass"])["subclass"].count()

isDGA  subclass
dga    bamital          2086
       cryptolocker    37254
       gameoverdga      8461
       goz              6136
       necurs           8331
       newgoz           9276
       nivdort          8456
legit  alexa           42616
       legit           37384
Name: subclass, dtype: int64

In [19]:
X = dga_dataset.drop(columns=["isDGA"])
X.head()

,domain,host,subclass,extension
0,6xzxsw3sokvg1tc752y1a6p0af,6xzxsw3sokvg1tc752y1a6p0af.com,gameoverdga,com
1,glbtlxwwhbnpxs,glbtlxwwhbnpxs.ru,cryptolocker,ru
2,xxmamopyipbfpk,xxmamopyipbfpk.ru,cryptolocker,ru
3,zfd5szpi18i85wj9uy13l69rg,zfd5szpi18i85wj9uy13l69rg.net,newgoz,net
4,jpqftymiuver,jpqftymiuver.ru,cryptolocker,ru

In [7]:
dga_dataset["isDGA_flag"] = dga_dataset["isDGA"].apply(lambda x: x == "dga")
dga_dataset.head()

,isDGA,domain,host,subclass,isDGA_flag
0,dga,6xzxsw3sokvg1tc752y1a6p0af,6xzxsw3sokvg1tc752y1a6p0af.com,gameoverdga,True
1,dga,glbtlxwwhbnpxs,glbtlxwwhbnpxs.ru,cryptolocker,True
2,dga,xxmamopyipbfpk,xxmamopyipbfpk.ru,cryptolocker,True
3,dga,zfd5szpi18i85wj9uy13l69rg,zfd5szpi18i85wj9uy13l69rg.net,newgoz,True
4,dga,jpqftymiuver,jpqftymiuver.ru,cryptolocker,True